---
- name: configure all servers
  hosts: nfs.tilda.net
  tasks:

          - name: create a group  ansible 
            group:
                    name: ansible
                    gid: 3001
                    state: present
             
          
          - name: configure ansible user
            user:
                    name: ansible
                    uid: 3001
                    group: ansible
                    groups: wheel
                    append: yes
                    state: present
                    password: "{{ 'student1' | password_hash( 'sha512' ) }}"
                    update_password: always


          - name: confifure sudo for user ansible
            copy:
                    dest: /etc/sudoers.d/ansible
                    content: 'ansible  ALL=(ALL) NOPASSWD: ALL'
            

